apiVersion: v1
kind: Secret
metadata:
  name: flask-secrets
  namespace: final
type: Opaque
stringData:
  DBHOST: mysql-db
  DBUSER: root
  DBPWD: password
  DATABASE: employees
  AWS_ACCESS_KEY_ID: {aws access key}
  AWS_SECRET_ACCESS_KEY: {AWS_SECRET_ACCESS_KEY}
  AWS_SESSION_TOKEN: {AWS_SESSION_TOKEN}
---

apiVersion: v1
kind: Secret
metadata:
  name: ecr-pull-secret
  namespace: final
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {dockerconfigjson}